GET http://localhost:7000

###
GET http://localhost:7000/about
###
GET http://localhost:7000/tickets
###
GET http://localhost:7000/asdgasd
###
GET http://localhost:7000/animals
###
POST http://localhost:7000/animals
Content-Type: application/json

{
  "name": "Lion",
  "count": 15
}
###
DELETE  http://localhost:7000/animals/2